- name: disbaling default redis
  ansible.builtin.command: dnf module disable redis -y

- name: enable redis
  ansible.builtin.command: dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: replace port number
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    backup: yes

- name: Change file ownership, group and permissions
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: enable and start redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
